pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Functions/AzureFunctionsTest.csproj'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Functions/AzureFunctionsTest.csproj'
    arguments: '-c Release -o ../build'
    zipAfterPublish: false
    modifyOutputPath: false
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/AzureFunctionsTest-$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/AzureFunctionsTest-$(Build.BuildId).zip'
    ArtifactName: 'AzureFunctionsTest'
    publishLocation: 'Container'