pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(Build.BinariesDirectory)/Functions/AzureFunctionsTest.csproj'
    feedsToUse: 'select'
    verbosityRestore: 'Diagnostic'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(Build.BinariesDirectory)/Functions/AzureFunctionsTest.csproj'
    arguments: '-c Release -o ../build'
    feedsToUse: 'select'
    verbosityRestore: 'Diagnostic'
    versioningScheme: 'off'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
