version: '3.4'
      
services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: SuperDuperPa$$wo3d
      MSSQL_PID: Express
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    restart: unless-stopped