// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteUnity.DataAccess.Context;

namespace DataAccess.Migrations
{
    [DbContext(typeof(PackagesDbContext))]
    [Migration("20190515201728_ExtendedPackageModel")]
    partial class ExtendedPackageModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WhiteUnity.DataAccess.Models.PackageDependencyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int?>("PackageModelId");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.HasIndex("PackageModelId");

                    b.ToTable("PackageDependencyModel");
                });

            modelBuilder.Entity("WhiteUnity.DataAccess.Models.PackageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedTimestamp");

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(300);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("LooksCount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Unity");

                    b.Property<string>("UrlForManifest")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("WhiteUnity.DataAccess.Models.PackageDependencyModel", b =>
                {
                    b.HasOne("WhiteUnity.DataAccess.Models.PackageModel")
                        .WithMany("Dependencies")
                        .HasForeignKey("PackageModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
